### ISSUE TITLE
[FR] Permit different KMS/Datastore Projects

### ISSUE THREAD

**Issue by davidebelloni** [RajeshHegde/gcredstash#2]
Hi,
it would be nice if it was possible to use a CryptoKey in project A and maintain secrets on Datastore in project B.

**Comment by RajeshHegde** [comment]
Hi @davidebelloni 
`KeyStore` takes project_id as a parameter and `GoogleKMS` also takes project_id as a parameter, if you want to use different project for Datastore and KMS then you can pass those to KeyStore and GoogleKMS. Let me know if that solves your problem.  But this wouldn't work in command-line.
